apiVersion: nais.io/v1
kind: Alert
metadata:
  name: secchamp-stats
  namespace: security-champion-admin
  labels:
    team: security-champion-admin
spec:
  receivers:
    slack:
      channel: '#security-champion-admin'
  alerts:
    - alert: Naisjob failed
      description: Naisjob secchamp-stats failed
      expr: kube_job_failed{job_name=~"^secchamp-stats.*", namespace="security-champion-admin"} > 0
      for: 1m
      action: "Check the logs"
      severity: warning
