apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: security-champion-admin
  name:  secchamp-stats
  namespace: security-champion-admin
spec:
  image: ghcr.io/navikt/secchamp-stats:c5f9e50
  schedule: "0 23 * * *"