name: Monitor dependencies with Dependabot
on:
  push:
    branches:
      - main
    paths:
      - "**.gradle.kts"
  workflow_dispatch:
jobs:
  dependabot:
    name: Monitor dependencies with Dependabot
    runs-on: ubuntu-20.04
    permissions: # The Dependency Submission API requires write permission
      contents: write
    steps:
      - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # ratchet:actions/checkout@v2
      - name: Run snapshot action
        uses: mikepenz/gradle-dependency-submission@aa82af7186ba17eb630a7d47c840ba8a3185ac91
        with:
          gradle-project-path: "gradle-example"
          gradle-build-module: ":app"
