name: Build and deploy main
on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
  workflow_dispatch:
jobs:
  build:
    name: Build all the things
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # ratchet:actions/checkout@v3
      - uses: actions/setup-java@f0bb91606209742fe3ea40199be2f3ef195ecabf # ratchet:actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'
      - uses: gradle/wrapper-validation-action@55e685c48d84285a5b0418cd094606e199cca3b6 # ratchet:gradle/wrapper-validation-action@v1
      - name: Build and test the app
        run: ./gradlew clean test shadowJar
      - name: Install cosign
        uses: sigstore/cosign-installer@4079ad3567a89f68395480299c77e40170430341 # ratchet:sigstore/cosign-installer@main
        with:
          cosign-release: 'v1.13.1'
      - name: Verify distroless base image
        run: cosign verify --key distroless.pub gcr.io/distroless/java17
      - name: Generate Docker image tag with short sha
        id: dockertag
        run: echo "docker_img=ghcr.io/${{ github.repository }}:$(git rev-parse --short HEAD)" >> $GITHUB_STATE
      - name: Login to GitHub Docker Registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # ratchet:docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push the Docker image
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5 # ratchet:docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.dockertag.outputs.docker_img }}
          cache-from: type=registry,ref=${{ steps.dockertag.outputs.docker_img }}
          cache-to: type=inline
  deploy_to_prod:
    name: Deploy to prod
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # ratchet:actions/checkout@v3
      - name: Generate Docker image tag
        id: dockertag
        run: echo "docker_img=ghcr.io/${{ github.repository }}:$(git rev-parse --short HEAD)" >> $GITHUB_STATE
      - uses: nais/deploy/actions/deploy@b8f4a51b3526b46ce68577a66bb4d6533a914eeb # ratchet:nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais.yaml,.nais/alerts.yaml
          IMAGE: ${{ steps.dockertag.outputs.docker_img }}
          VARS: .nais/prod.yaml
