name: Monitor dependencies with Snyk
on:
  push:
    branches:
      - main
    paths:
      - "**.gradle.kts"
  workflow_dispatch:
jobs:
  build:
    name: Monitor dependencies with Snyk
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # ratchet:actions/checkout@v2
      - uses: actions/setup-java@f0bb91606209742fe3ea40199be2f3ef195ecabf # ratchet:actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Install Snyk CLI
        uses: snyk/actions/setup@4259725f0dd662aa764d82760cca8959888a595c # ratchet:snyk/actions/setup@master
      - name: Monitor dependencies with Snyk
        run: snyk monitor --org=security-champion-admin
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
